---
title: "LSOA Geodemographic Harmonization"
author: "Cameron Ward / Akos Balog"
date: '2023-06-27'
output: html_document
description: "Harmonizes LSOA (2011) to LSOA (2021) boundaries using ONS lookups and spatial PWC (Population Weighted Centroid) matching."
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(data.table)
require(tidyverse)
require(stringr)
require(sf)
require(RANN)
```

## 1. Load Lookups
Loading the exact fit lookups for England and Wales (v3).

```{r}
# Use relative paths from repo root
lookup_path <- "../data/LSOA_(2011)_to_LSOA_(2021)_to_Local_Authority_District_(2022)_Exact_Fit_Lookup_for_EW_(V3).csv"

if (file.exists(lookup_path)) {
  LSOA2011 <- read.csv(lookup_path, fileEncoding="UTF-8-BOM") %>%
    select(1:7) %>%
    rename(CHG21 = CHGIND)
  
  df <- LSOA2011
  
  df <- df %>%
    mutate(LSOAXXCD = NA) %>%
    mutate(LSOAXXCD = ifelse(CHG21 == "U", LSOA21CD, LSOAXXCD)) %>%
    mutate(LSOAXXCD = ifelse(CHG21 == "M", LSOA21CD, LSOAXXCD)) %>%
    mutate(LSOAXXCD = ifelse(CHG21 == "S", LSOA11CD, LSOAXXCD))
} else {
  stop("Lookup file not found in ../data/")
}
```

## 2. Spatial Matching (Nearest Neighbor)
For LSOAs that cannot be matched exactly, we use Population Weighted Centroids (PWC) and nearest neighbor matching.

```{r}
pts11_path <- "../data/LSOA_Dec_2011_PWC_in_England_and_Wales_2022_1923591000694358693.csv"
pts21_path <- "../data/LLSOA_Dec_2021_PWC_for_England_and_Wales_2022_1028145039677403461.csv"

if (file.exists(pts11_path) && file.exists(pts21_path)) {
  pts11 <- read.csv(pts11_path) %>%
    select(x, y, LSOA11CD) %>%
    semi_join(df %>% filter(is.na(LSOAXXCD)), by = "LSOA11CD")

  pts21 <- read.csv(pts21_path) %>%
    select(x, y, LSOA21CD) %>%
    semi_join(df %>% filter(is.na(LSOAXXCD)), by = "LSOA21CD")

  i <- nn2(data = pts11 %>% select(-LSOA11CD),
           query = pts21 %>% select(-LSOA21CD),
           k = 1)$nn.idx[,1]

  df <- left_join(df,
                  data.frame(LSOA21CD = pts21$LSOA21CD, nearest = pts11$LSOA11CD[i]),
                  by = "LSOA21CD") %>%
    mutate(LSOAXXCD = ifelse(!is.na(nearest), nearest, LSOAXXCD)) %>%
    select(-nearest)
}
```

## 3. Generate Harmonized IDs

```{r}
df |>
  select(LSOAXXCD) |>
  filter(!duplicated(LSOAXXCD)) -> gps
data.frame(LSOAXXCD = gps$LSOAXXCD, i = 1: nrow(gps)) -> gps

df |>
  left_join(gps, by = "LSOAXXCD") |>
  mutate(i = str_pad(i, width = 7, pad = "0")) |>
  mutate(LSOAXXCD = paste0("X", i, substr(LSOAXXCD, 1, 1))) |>
  select(-i) -> df
```

## 4. Export Lookups

```{r}
# Exports local files for use in clustering
write_csv(df, "../data/LSOAXXCD_full_lookup.csv")
```

## 5. Boundary File Creation
Aggregating 2021 LSOA census boundaries to harmonized units for mapping.

```{r}
# Path to GeoJSON/Shp
boundary_path <- "../data/Lower_layer_Super_Output_Areas_(December_2021)_Boundaries_EW_BFC_(V10).shp"

if (file.exists(boundary_path)) {
  map <- st_read(boundary_path) |>
    left_join(df |> select(LSOAXXCD, LSOA21CD) |> unique(), by = "LSOA21CD")
  
  # Aggregate to LSOAXXCD
  map_aggregated <- map %>%
    group_by(LSOAXXCD) %>%
    summarize(geometry = st_union(geometry)) %>%
    ungroup()
    
  st_write(map_aggregated, "../data/harmonized_boundaries.geojson", delete_dsn = TRUE)
}
```